### ISSUE TITLE
Desktop Client 1.4.0 Discrepancy between "My Accounts" balance and actual Address Balance

### ISSUE THREAD

**Issue by ArkPotato** [ArkEcosystem/ark-desktop#329] opened 2017-10-09 23:37 UTC
The "My Accounts" balance is showing a greater balance compared to the actual balance on my wallet. For me it is showing a balance 2.6k greater. I have talked to peers and they seem to have the same issue but with a different discrepancy.
Desktop client 1.4.0 on Mac OSX

**Comment by ArkPotato** [comment] 2017-10-09 23:50
![balance disrep](https://user-images.githubusercontent.com/32655723/31363233-d9432840-ad11-11e7-9483-f4d06fdb4441.jpg)

**Comment by j-a-m-l** [comment] 2017-10-09 23:55
In the past I've suffer this problem, but now I'm not able to reproduce it.

@ArkPotato could you elaborate more? do you have any contact, delegate, etc?

**Comment by ArkPotato** [comment] 2017-10-09 23:57
@j-a-m-l 
No contacts, vote for Biz_Classic,  have two wallets one with 0 Balance.

**Comment by luciorubeens** [comment] 2017-10-10 00:00
@ArkPotato do you have ledger accounts?

**Comment by ArkPotato** [comment] 2017-10-10 00:03
@luciorubeens no, no trezor or ledger or anything like that. Only thing i've done is Download wallet, Vote, and transfer funds here and there.

**Comment by j-a-m-l** [comment] 2017-10-10 00:14
I think that I've found the problem!

When the user set the account label to the exact name that a delegate, then the app, gets the balance of the delegate (at least that has produced wrong balances for me on DEVNET).

@ArkPotato do you have uses account labels?

**Comment by ArkPotato** [comment] 2017-10-10 00:16
@j-a-m-l Unfortunately, no, I do not use any labels

**Comment by yonseiyes** [comment] 2017-10-10 07:16
I have the same problem... I use account label.

**Comment by liamreoch** [comment] 2017-10-10 09:00
I've made a PR with a fix for this issue.

**Comment by luciorubeens** [comment] 2017-10-11 11:09
Fixed in #330

**Closed by luciorubeens** 2017-10-11 11:09 UTC
Labels: Priority: High, Type: Bug
