### ISSUE TITLE
Windows x64 1.3.2 Not Responding

### ISSUE THREAD

**Issue by hmmdeif** [ArkEcosystem/ark-desktop#263] opened 2017-09-13 22:03 UTC
Fresh install of Ark Desktop client. Open it, it takes about 1 minute for the background processes to show the client window. Then it goes into 'Not Responding' mode where the cursor is a round loading circle.

Eventually the stats on the wallet load and I click on 'Create Account'. A few minutes later it loads up the pass phrase but it takes forever for anything to respond. In order to close I have to end the task in Task Manager.

Windows 10
Ark Desktop - Windows x64 1.3.2

More info reported by users on [reddit](https://www.reddit.com/r/ArkEcosystem/comments/6y68h5/cant_get_the_ark_wallet_to_work/) and the [ark forum](https://forum.ark.io/topic/384/ark-client-not-responding).

**Comment by SBero** [comment] 2017-09-14 05:49
I'll give this a try on my Windows 10 VM, see what happens.

**Comment by SBero** [comment] 2017-09-14 07:13
I tried on my Windows 10 VM. I couldn't replicate the issue your having. So my questions:

- Are you using a Ledger Nano S?
- Are you using a dedicated connection to the internet?
- What version of the app do you have to roll back to for it to work? I read on the reddit post you provided, 1.2.2.

**Comment by hmmdeif** [comment] 2017-09-14 13:20
I'll work my way back with the versions tonight to give you the exact version that it started (in a few hours).

To answer your other questions:
* No Ledger Nano S, just using the Desktop Wallet
* It's a normal internet connection through a router, modem, and copper wire to the exchange. I have tried using a VPN and without. Nothing else is being used but the network usage is negligible when I see what it's doing. CPU, GPU, SSD are all sitting on 0% usage when I load the client.

**Comment by hmmdeif** [comment] 2017-09-14 23:04
OK I found the issue. It started in 1.3.0 because that's when you guys brought in `ledgerco`. I'm getting blocking calls when `HID.devices()` is being called, and since you guys have it checking on a loop for the Ledger Nano S (I assume that's what you're checking for), it blocks constantly, returns, then immediately checks again.

I don't know enough C to see why it's doing it all the way down in the `node-hid` module, but that's where the issue seems to be.

Perhaps push this to a background process using `child_process.fork` and send messages to the main thread once it returns? In the meantime I'm just going to comment out the device check on my code as I don't have a Ledger Nano S. Perhaps release a Windows version marked "Without Ledger Support" as a quick fix for those of us with issues?

**Comment by SBero** [comment] 2017-09-15 03:52
I figured it may have revolved around the ledger integration.

Looking at it, it's checking every 1s to see if there's a ledger device connected, so maybe this interval is just triggering execution one after another for some users?

Maybe if this interval was longer it'd fix the issue? 

Without a ledger nano s, can't be certain i'll have the right fix. I've looked into the ledgerco API, and there's no callback available for connected devices to eliminate the interval, so doing as you say, and having the check and setup of it as a forked child process may be the only way to go.

**Comment by fix** [comment] 2017-09-15 09:20
Just made some review with ledgerHQ. Seems that node-hid might block on some platforms, so the idea would be to spawn a thread using `child_process.fork` and handle communication to ledger through this thread.

If it solves the issue it would be great to then backtrack this idea at the `ledgerco` lib level through a PR. Maybe even test this right now at this level.

Anybody on it?

**Comment by hmmdeif** [comment] 2017-09-15 09:30
@SBero Just to add to your point on making the interval longer, it would have to be at least 20 seconds because that's how long it takes to return for me, and even then it's fully blocking the main thread so the interval doesn't really matter.

**Comment by fix** [comment] 2017-09-15 09:34
@hmmdeif are you able to test somehow a quick and dirty npm script to see if `child_process.fork`could solve the issue on your windows?

**Comment by hmmdeif** [comment] 2017-09-15 10:52
The above pull request is a good start I think, but it probably needs someone with a ledger to close it out as I'll be coding blindly within `LedgerArk` to move all the function calls and responses into serialized messages within a child process.

**Comment by carlos5577** [comment] 2017-09-17 17:51
`Log Name:      Application
Source:        Application Hang
Date:          9/17/2017 12:43:30 PM
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      carlos5577v2
Description:
The program ArkClient.exe version 1.3.2.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 3298
 Start Time: 01d32fdc4357a6d9
 Termination Time: 329
 Application Path: C:\Program Files\ArkClient\ArkClient.exe
 Report Id: e565e04e-b7df-482d-bef9-7cec5e1d7bef
 Faulting package full name: 
 Faulting package-relative application ID: 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-09-17T17:43:30.513853500Z" />
    <EventRecordID>915239</EventRecordID>
    <Channel>Application</Channel>
    <Computer>carlos5577v2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ArkClient.exe</Data>
    <Data>1.3.2.0</Data>
    <Data>3298</Data>
    <Data>01d32fdc4357a6d9</Data>
    <Data>329</Data>
    <Data>C:\Program Files\ArkClient\ArkClient.exe</Data>
    <Data>e565e04e-b7df-482d-bef9-7cec5e1d7bef</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Binary>55006E006B006E006F0077006E0000000000</Binary>
  </EventData>
</Event>`
Here is my log it helps. I'm also having this issue.

**Comment by fix** [comment] 2017-09-18 08:02
@carlos5577 We have a fix now merged into master. Is it possible for you to pull a development env and try this solution?

**Comment by carlos5577** [comment] 2017-09-18 18:08
Alright it worked cloning the master branch.

**Comment by fix** [comment] 2017-09-18 20:36
ok great news!

**Comment by doubled1c3** [comment] 2017-09-19 04:02
I have experienced the same issue, Hangs heavily on Win7 Ultimate x64, works great on random computer with Win10 x64.  What is the timeframe to releasing an installer with fix integrated?

Ark for life

**Comment by doubled1c3** [comment] 2017-09-19 20:03
I confirmed 1.2.2 working fine on the problem PC, if this helps. Cheers!

**Closed** 2017-10-17 17:41 UTC
