### ISSUE TITLE
Managing contacts from Explorer view

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/ark-desktop#550] opened 2018-02-03 08:18 UTC
When trying to add contacts (especially ones who make transactions with you) there is no way to "Add to contacts" function. 

One must tediously copy the address, open contacts, add new contact and paste in the address and fill in the name.

The UX friendly way to enhance this experience is to add a button to every address or a right click menu option for adding the selected address to contacts.

Please make it easier to add people to ones contacts.

**Comment by luciorubeens** [comment] 2018-02-03 09:53
I agree, it would be useful.

**Comment by alexbarnsley** [comment] 2018-02-03 15:20
#470

**Comment by alexbarnsley** [comment] 2018-02-04 10:32
Duplicate of #530. Will close the other one as this has more info, however this has been solved in #470 which is due to be merged soon.

**Closed** 2018-02-05 15:03 UTC
Labels: Type: Feature Request
