### ISSUE TITLE
When trying to send big amount of text in vendor field the tx can be sent but is not confirmed and nothing happens.

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/ark-desktop#16] opened 2016-11-28 19:04 UTC

**Comment by fix** [comment] 2016-11-30 11:11
yes needs to enforce 64bytes length

**Comment by Doweig** [comment] 2017-02-01 05:22
Duplicate of https://github.com/ArkEcosystem/ark-desktop/issues/8

**Closed by Doweig** 2017-02-01 05:22 UTC
Labels: Type: Bug
