### ISSUE TITLE
Transactions disappearing (reproducible on Windows 10 and macOS 13.1 (High Sierra))

### ISSUE THREAD

**Issue by rdk1979** [ArkEcosystem/ark-desktop#403] opened 2017-11-16 17:26 UTC
To reproduce the bug:

1) Open the ARK-client
2) Click your ARK address and you'll get onto your transaction-list by default
3) Click your address again on the left-menu under "My accounts"

Sometimes you need to click 2 times on the address it seems, but then 70% of the transactions disappears. it happens when running the client windowed mode as well as in full-screen.

To get back to a good view you'll click "Ark Client 1.4.1" in top left corner and your address again. Then you'll see your full list of transactions again.

This happens on Windows 10 and also macOS 13.1 at least and it seems to be related to 4K resolution. When I resize the windows to less than a quarter of the screen (so Full HD or smaller actually) then this bug doesn't pop up anymore.

Not bugged:
<img width="1679" alt="not bugged" src="https://user-images.githubusercontent.com/33729261/32905848-75821e76-cafb-11e7-9bd1-e045480c5287.png">

Bugged screen:
<img width="1657" alt="bugged" src="https://user-images.githubusercontent.com/33729261/32905846-7550b7e6-cafb-11e7-874b-93afad5ed315.png">

**Comment by j-a-m-l** [comment] 2017-11-17 00:53
The cause is https://github.com/sroze/ngInfiniteScroll/issues/312. I'll try [virtualRepeat](https://material.angularjs.org/latest/demo/virtualRepeat) as it's suggested there.

**Comment by rdk1979** [comment] 2017-11-17 07:21
High j-a-m-l please notice that it's not the scrollbar that disappears in the first place. It's the transactions that disappear right after clicking the address again. And then of course, because the transactions aren't enough anymore to fill up the screen the scrollbar disappears too.

**Comment by zillionn** [comment] 2017-11-17 12:11
ArkClient 1.4.1 - I was able to reproduce it on Windows 10 but on Mac OS 10.11.6 everything is fine.

**Comment by rdk1979** [comment] 2017-11-17 12:19
@zillionn  Thanks for reproducing it. On El Capitan also with a 4K or 5K screen-resolution?

**Comment by zillionn** [comment] 2017-11-17 12:33
Built-in Display Retina 13.3-inch (2560 x 1600)
2nd display LG ULTRAWIDE 28.5-inch (2560 x 1080)

It works on both. Not sure if the display is the problem. I'll dig a little bit more on the Win version.

**Comment by rdk1979** [comment] 2017-11-17 12:42
@zillionn  well it seems to be related to 4K (5K on iMac) resolution, you don't have that i see. 5K is a resolution of 5120x2880. The bug seems to disappear with a resolution of 2560x1440 or lower. (i should figure the exact limit to be more accurate)

 So on your mac it might happen on fullscreen mode, but not in a small window mode. (in theory... not sure!)

**Comment by zillionn** [comment] 2017-11-17 13:13
I found out what is happening. When the innerHeight is up to 975px the scroll is visible but when I resize it to >975px it disappears.

**Comment by rdk1979** [comment] 2017-11-17 13:24
i don't touch anything... it's not the scrollbar that disappears. The transactions disappear. You can see that on my shots, the white at the "bugged" shot. I don't touch the scrollbar at all, i only click the ARK address. And of course... the scrollbar disappears too because there aren't enough transactions anymore to fill up even one screen, so no reason to have a scroll.

**Comment by zillionn** [comment] 2017-11-17 13:24
The problem occurs because when you click the address from the dashboard it loads 20 txs, but when you click on the address in My Accounts menu it loads only 10.

**Comment by rdk1979** [comment] 2017-11-17 13:28
I have more than 20 tx at first, about 50... and saying only 10 txs load when you click the address on the left makes no sense to me also. Than it would matter which resolution... than it would just load 10 txs by design no matter what screensize or resolution.

**Comment by zillionn** [comment] 2017-11-17 13:31
I see. Then it's probably something with this infinite scroll.

**Comment by rdk1979** [comment] 2017-11-19 00:48
This issue is also not fixed in wallet-update 1.4.2, the behaviour is still exactly the same. In macOS 13.1 as well as on Windows 10 Fall Creators Edition.

**Comment by boldninja** [comment] 2017-11-19 00:53
@rdk1979 Yeah cause they are still working on a solution will be included in the next release when its coded and tested.

**Comment by rdk1979** [comment] 2017-11-19 00:54
@boldninja Thanks! Yes... it was expected, but Alex wanted to be sure. And I promised to test it and give feedback about it. So this wasn't related to the infinitescroll-bug.

**Closed** 2017-11-21 11:53 UTC
Labels: Status: Accepted, Type: Small bug

**Comment by rdk1979** [comment] 2017-11-22 13:43
Confirmed... bug is gone in ARK-client 1.4.3 on macOS 13.1 as well as Windows 10 (FC update).
