### ISSUE TITLE
Feature request: Automated payments/ rules

### ISSUE THREAD

**Issue by Zeehenk** [ArkEcosystem/ark-desktop#202] opened 2017-08-16 10:56 UTC
Hi everyone,

I'm a total n00b with coding (read: I can't do it at all), but I would like to see what's possible with this request. Firstly my issue:

I have voted for a delegate, but this dalegate has capped my max voting weight. This means that I have made a second wallet for voting with my remaining ARK.
I am getting weekly payments by the first delegate to my "capped wallet", but I want to get this payout to my second walled directly. What I would like to set up are some rules like I can do with Outlook. For example for this:

If ARK received from [ADDRESS], than [SEND] [SAME AMOUNT ARK] to [ADDRESS]

I think this would be a great feature for people (like me) who can't code. Even one line of code seems scary for me to do... I'm too afraid to make mistakes in there and lose my ARK.

Obviously this "RULE" feature is not limited to above example. You could have rules to only send ark if you received an X amount from a particular address etc....

Hope I explained everything well enough :)

Cheers!

**Comment by fileninja** [comment] 2017-08-16 11:03
Maybe Duplicate of #180

**Comment by Zeehenk** [comment] 2017-08-16 11:44
Thanks, posted it there too

**Comment by luciorubeens** [comment] 2017-08-17 02:37
Let's keep in #180

**Closed by luciorubeens** 2017-08-17 02:37 UTC
