### ISSUE TITLE
Save function when leaving client desktop (still running)

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#30] opened 2016-12-10 20:54 UTC
might be useful if it saves an incomplete transaction rather than starting fresh every time you leave the client (whilst it's still open)

**Comment by Doweig** [comment] 2017-02-01 04:25
Steps I've taken to try to reproduce the bug:
Start a transaction, popup open with 4 fields (addr, amount, smartbridge, passphrase), fill the first 2, switch to another window, come back, fields are still there.
I you click outside the popup (but still inside the ark-desktop window) then the popup disappears is that your behavior?

**Comment by Doweig** [comment] 2017-02-01 05:11
Looks like a duplicate of https://github.com/ArkEcosystem/ark-desktop/issues/5

**Closed by Doweig** 2017-02-01 05:11 UTC
Labels: Type: Bug
