### ISSUE TITLE
Unable to send 1.1 Ark

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-desktop#87] opened 2017-04-21 13:18 UTC
I tried to send exactly 1.1 Ark.
The Amount turns red and the next button can't be pressed.
If I change the amount to anything else it mostly works. 
But there are other number with that problem. (Example 1.12 or 1.102 do not work neither)

**Comment by fix** [comment] 2017-04-25 20:50
closing as duplicate of #78

**Closed by fix** 2017-04-25 20:50 UTC
Labels: Priority: High, Type: Bug
