### ISSUE TITLE
Click area for some buttons aren't consistent

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-desktop#51] opened 2017-03-06 17:38 UTC
Most of the buttons can be clicked in the area surrounding the text, for example, "Minify", "Maximize" and "Full Screen" under the power button icon. Other buttons you need to click on the text itself, "Close", "Restart" and the language button.

**Comment by dafty235** [comment] 2017-03-06 17:41
Somewhat related to #46

**Comment by Doweig** [comment] 2017-03-08 08:40
For example in the screenshot below I can click anywhere on the dark grey area to close, not only the text. Can you confirm your behavior is different than mine

<img width="438" alt="screen shot 2017-03-08 at 4 38 48 pm" src="https://cloud.githubusercontent.com/assets/1850848/23696220/be850bc4-041d-11e7-9fd3-dae7463e9dba.png">

**Comment by dafty235** [comment] 2017-03-08 09:28
![avsfn3](https://cloud.githubusercontent.com/assets/24987593/23697920/826e622a-03e1-11e7-97e7-6371e6675e45.gif)

**Comment by dafty235** [comment] 2017-03-08 09:31
https://drive.google.com/file/d/0B6Bac9ruPatPd0o5aExyTm5WUnc/view?usp=sharing

**Comment by Doweig** [comment] 2017-03-21 07:10
Duplicate of #46

**Closed by Doweig** 2017-03-21 07:10 UTC
Labels: Status: Help Wanted, Type: Bug
