### ISSUE TITLE
Losing details in send form

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-desktop#31] opened 2016-12-10 20:55 UTC
if you need to move from the main screen in desktop client to copy something from desktop the send screen disappears and you appear to need to start over...

**Comment by Doweig** [comment] 2017-02-01 05:12
Duplicate of https://github.com/ArkEcosystem/ark-desktop/issues/5

**Closed by Doweig** 2017-02-01 05:12 UTC
Labels: Type: Bug
